export const categories = [
  {
    slug: "stationery",
    en: "Writing & Pens",
    mr: "लेखन साहित्य व पेन",
    symbol: "✎",
  },
  {
    slug: "paper",
    en: "Notebooks & Paper",
    mr: "वह्या व कागद",
    symbol: "▤",
  },
  {
    slug: "office",
    en: "Office Supplies",
    mr: "कार्यालयीन साहित्य",
    symbol: "▣",
  },
  {
    slug: "art-craft",
    en: "Art & Craft",
    mr: "कला व हस्तकला",
    symbol: "✦",
  },
  {
    slug: "staples",
    en: "Atta, Rice & Dal",
    mr: "पीठ, तांदूळ व डाळ",
    symbol: "🌾",
  },
  { slug: "dairy", en: "Dairy & Breakfast", mr: "दूध व नाश्ता", symbol: "🥛" },
  {
    slug: "snacks",
    en: "Snacks & Biscuits",
    mr: "स्नॅक्स व बिस्किटे",
    symbol: "🍪",
  },
  { slug: "beverages", en: "Tea & Beverages", mr: "चहा व पेये", symbol: "☕" },
  {
    slug: "cooking",
    en: "Cooking Essentials",
    mr: "स्वयंपाक साहित्य",
    symbol: "🫙",
  },
  {
    slug: "household",
    en: "Home & Cleaning",
    mr: "घर व स्वच्छता",
    symbol: "🧹",
  },
  { slug: "personal", en: "Personal Care", mr: "वैयक्तिक निगा", symbol: "🧴" },
];
export const seedProducts = [
  {
    slug: "everyday-basmati-rice",
    en: "Everyday Basmati Rice",
    mr: "रोजचा बासमती तांदूळ",
    brand: "PANTRY SELECT",
    category: "staples",
    pack: "1 kg",
    unit: "kg",
    quantity: 1,
    price: 10900,
    mrp: 14000,
    aliases: ["rice", "chawal", "तांदूळ", "tandul", "basmati"],
    symbol: "🌾",
    color: "#f4e9c9",
  },
  {
    slug: "whole-wheat-atta",
    en: "Whole Wheat Atta",
    mr: "संपूर्ण गव्हाचे पीठ",
    brand: "PANTRY SELECT",
    category: "staples",
    pack: "5 kg",
    unit: "kg",
    quantity: 5,
    price: 24500,
    mrp: 28500,
    aliases: ["atta", "flour", "पीठ", "aata", "wheat"],
    symbol: "🌾",
    color: "#f6dfcf",
  },
  {
    slug: "toor-dal",
    en: "Unpolished Toor Dal",
    mr: "तूर डाळ",
    brand: "PANTRY SELECT",
    category: "staples",
    pack: "1 kg",
    unit: "kg",
    quantity: 1,
    price: 15900,
    mrp: 18500,
    aliases: ["dal", "daal", "तूर", "डाळ", "lentils"],
    symbol: "🫘",
    color: "#f5dfb4",
  },
  {
    slug: "fresh-toned-milk",
    en: "Fresh Toned Milk",
    mr: "ताजे टोन्ड दूध",
    brand: "MORNING MEADOW",
    category: "dairy",
    pack: "500 ml",
    unit: "ml",
    quantity: 500,
    price: 2800,
    mrp: 3000,
    aliases: ["milk", "doodh", "dudh", "दूध"],
    symbol: "🥛",
    color: "#daecf5",
  },
  {
    slug: "sunflower-oil",
    en: "Refined Sunflower Oil",
    mr: "सूर्यफूल तेल",
    brand: "GOLDEN DROP",
    category: "cooking",
    pack: "1 litre",
    unit: "l",
    quantity: 1,
    price: 13500,
    mrp: 16500,
    aliases: ["oil", "tel", "तेल"],
    symbol: "🌻",
    color: "#f5e69e",
  },
  {
    slug: "premium-leaf-tea",
    en: "Premium Leaf Tea",
    mr: "प्रीमियम चहा",
    brand: "HILL & CUP",
    category: "beverages",
    pack: "250 g",
    unit: "g",
    quantity: 250,
    price: 12500,
    mrp: 15000,
    aliases: ["tea", "chai", "चहा"],
    symbol: "🍃",
    color: "#dce8cc",
  },
  {
    slug: "butter-cookies",
    en: "Classic Butter Cookies",
    mr: "बटर बिस्किटे",
    brand: "LITTLE OVEN",
    category: "snacks",
    pack: "200 g",
    unit: "g",
    quantity: 200,
    price: 4500,
    mrp: 6000,
    aliases: ["biscuit", "cookies", "बिस्किटे"],
    symbol: "🍪",
    color: "#efdbc3",
  },
  {
    slug: "laundry-detergent",
    en: "Fresh Laundry Detergent",
    mr: "कपडे धुण्याची पावडर",
    brand: "HOME BRIGHT",
    category: "household",
    pack: "1 kg",
    unit: "kg",
    quantity: 1,
    price: 11900,
    mrp: 14500,
    aliases: ["detergent", "washing", "पावडर"],
    symbol: "🫧",
    color: "#d6e9f2",
  },
  {
    slug: "aloe-handwash",
    en: "Aloe Gentle Handwash",
    mr: "अ‍ॅलो हँडवॉश",
    brand: "DAILY KIND",
    category: "personal",
    pack: "250 ml",
    unit: "ml",
    quantity: 250,
    price: 7900,
    mrp: 9900,
    aliases: ["soap", "handwash", "साबण"],
    symbol: "🧴",
    color: "#d7e8dc",
  },
  {
    slug: "thick-poha",
    en: "Thick Poha",
    mr: "जाड पोहे",
    brand: "PANTRY SELECT",
    category: "staples",
    pack: "500 g",
    unit: "g",
    quantity: 500,
    price: 4500,
    mrp: 5500,
    aliases: ["poha", "पोहे", "flattened rice"],
    symbol: "🌾",
    color: "#f1e7c9",
  },
  {
    slug: "pure-ghee",
    en: "Pure Cow Ghee",
    mr: "शुद्ध गायीचे तूप",
    brand: "MORNING MEADOW",
    category: "dairy",
    pack: "500 ml",
    unit: "ml",
    quantity: 500,
    price: 29900,
    mrp: 34000,
    aliases: ["ghee", "तूप", "tup"],
    symbol: "🧈",
    color: "#f6e7b7",
  },
  {
    slug: "iodised-salt",
    en: "Iodised Salt",
    mr: "आयोडीनयुक्त मीठ",
    brand: "PANTRY SELECT",
    category: "cooking",
    pack: "1 kg",
    unit: "kg",
    quantity: 1,
    price: 2400,
    mrp: 2800,
    aliases: ["salt", "namak", "मीठ", "mith"],
    symbol: "🧂",
    color: "#deeaed",
  },
  {
    slug: "a5-hardcover-notebook",
    en: "A5 Hardcover Notebook",
    mr: "ए५ हार्डकव्हर वही",
    brand: "PAPER & CO.",
    category: "paper",
    pack: "192 ruled pages",
    unit: "piece",
    quantity: 1,
    price: 18900,
    mrp: 22000,
    aliases: ["notebook", "diary", "journal", "वही", "notepad"],
    symbol: "▤",
    color: "#dce6e2",
  },
  {
    slug: "smooth-ball-pen-set",
    en: "Smooth Ball Pen Set",
    mr: "स्मूथ बॉल पेन संच",
    brand: "WRITEWELL",
    category: "stationery",
    pack: "Pack of 5 · blue",
    unit: "piece",
    quantity: 5,
    price: 5500,
    mrp: 6500,
    aliases: ["pen", "ball pen", "blue pen", "पेन", "writing"],
    symbol: "✎",
    color: "#e9d9d3",
  },
  {
    slug: "a4-copier-paper",
    en: "A4 Copier Paper",
    mr: "ए४ कॉपियर पेपर",
    brand: "OFFICE SELECT",
    category: "paper",
    pack: "75 GSM · 500 sheets",
    unit: "piece",
    quantity: 1,
    price: 36500,
    mrp: 39900,
    aliases: ["a4", "paper", "printer paper", "कागद", "xerox"],
    symbol: "□",
    color: "#d9e0e4",
  },
  {
    slug: "metal-stapler-no-10",
    en: "Metal Stapler No. 10",
    mr: "मेटल स्टेपलर नं. १०",
    brand: "DESKLINE",
    category: "office",
    pack: "1 stapler · pin box included",
    unit: "piece",
    quantity: 1,
    price: 14000,
    mrp: 16500,
    aliases: ["stapler", "staple pins", "office", "स्टेपलर"],
    symbol: "⌁",
    color: "#d8dfce",
  },
  {
    slug: "document-file-set",
    en: "Document File Set",
    mr: "डॉक्युमेंट फाईल संच",
    brand: "FILEWISE",
    category: "office",
    pack: "Pack of 3 · A4",
    unit: "piece",
    quantity: 3,
    price: 12900,
    mrp: 15000,
    aliases: ["file", "folder", "document file", "फाईल", "office"],
    symbol: "▱",
    color: "#d7e3e7",
  },
  {
    slug: "permanent-marker-set",
    en: "Permanent Marker Set",
    mr: "परमनंट मार्कर संच",
    brand: "WRITEWELL",
    category: "stationery",
    pack: "Pack of 4 · assorted",
    unit: "piece",
    quantity: 4,
    price: 12000,
    mrp: 14500,
    aliases: ["marker", "permanent marker", "sketch pen", "मार्कर"],
    symbol: "╱",
    color: "#eadcc9",
  },
  {
    slug: "sticky-notes-set",
    en: "Sticky Notes Set",
    mr: "स्टिकी नोट्स संच",
    brand: "PAPER & CO.",
    category: "paper",
    pack: "5 colours · 400 sheets",
    unit: "piece",
    quantity: 1,
    price: 9900,
    mrp: 12000,
    aliases: ["sticky notes", "post it", "memo", "नोट्स"],
    symbol: "◩",
    color: "#e6e0bd",
  },
  {
    slug: "washable-colour-pencil-set",
    en: "Colour Pencil Set",
    mr: "रंगीत पेन्सिल संच",
    brand: "MAKE & PLAY",
    category: "art-craft",
    pack: "12 colours",
    unit: "piece",
    quantity: 12,
    price: 17500,
    mrp: 19900,
    aliases: ["colour pencil", "drawing", "art", "रंगीत पेन्सिल"],
    symbol: "✦",
    color: "#ead5ce",
  },
] as const;
